version: '3.8'
services:
  redis:
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--appendfilename", "appendonly.aof"]
    ports:
      - "6379:6379" # expose for dev host access (optional)

volumes:
  redis_data:
    driver: local
