name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - os: ubuntu-22.04
              php: '8.1'
            - os: ubuntu-22.04
              php: '8.2'
            - os: ubuntu-22.04
              php: '8.3'
            - os: ubuntu-22.04
              php: '8.4'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer
        run: composer --version

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml
